In [3]:
import numpy as np

In [7]:
arr = np.linspace (1,10,10, dtype='int8')
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [9]:
indice_cond= arr>5
indice_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [12]:
arr[arr>5] =80
arr

array([ 1,  2,  3,  4,  5, 80, 80, 80, 80, 80], dtype=int8)

In [14]:
arr[arr<8]=20
arr

array([20, 20, 20, 20, 20, 80, 80, 80, 80, 80], dtype=int8)

In [15]:
arr[arr==80]

array([80, 80, 80, 80, 80], dtype=int8)

In [18]:
arr[arr<10]=30
arr

array([20, 20, 20, 20, 20, 80, 80, 80, 80, 80], dtype=int8)