In [3]:
import numpy as np

In [7]:
arr = np.linspace (1,10,10, dtype='int8')
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
# regresa un array de booleanos donde la condicion se cumple

In [9]:
indice_cond= arr>5
indice_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# Multiples condiciones

In [10]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
# Modificar los valores que cumplen la condición

In [12]:
arr[arr>5] =80
arr

array([ 1,  2,  3,  4,  5, 80, 80, 80, 80, 80], dtype=int8)

In [14]:
arr[arr<8]=20
arr

array([20, 20, 20, 20, 20, 80, 80, 80, 80, 80], dtype=int8)

In [15]:
arr[arr==80]

array([80, 80, 80, 80, 80], dtype=int8)

In [18]:
arr[arr<10]=30
arr

array([20, 20, 20, 20, 20, 80, 80, 80, 80, 80], dtype=int8)

In [37]:
arr =np.linspace (1,20,10,  dtype = 'int8' )
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20], dtype=int8)

In [41]:
indices_cond =arr>9
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[indices_cond]

array([11, 13, 15, 17, 20], dtype=int8)

In [44]:
arr[(arr<13) &(arr>5)]


array([ 7,  9, 11], dtype=int8)

In [52]:
arr[(arr/2)]

IndexError: arrays used as indices must be of integer (or boolean) type

In [33]:
arr=arr
arr

[array([False, False, False, False, False,  True,  True,  True,  True,
         True])]