In [1]:
import numpy as np

In [13]:
arr = np.arange (0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy =arr.copy()

In [27]:
arr_copy[:]=100

In [28]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [23]:
trozo_de_arr=arr [0:6]

In [24]:
trozo_de_arr[:]=0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [25]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [26]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [31]:
array = np.arange(1,12)

In [32]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
array_copy = array.copy()

In [34]:
array_copy[:]=100

In [35]:
array_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [36]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
mitad_array =array[1:6]

In [38]:
mitad_array

array([2, 3, 4, 5, 6])

In [39]:
mitad_copy =mitad_array.copy()

In [40]:
mitad_array[:]=85

In [41]:
mitad_array

array([85, 85, 85, 85, 85])

In [42]:
array

array([ 1, 85, 85, 85, 85, 85,  7,  8,  9, 10, 11])

In [43]:
mitad_array

array([85, 85, 85, 85, 85])