In [1]:
import numpy as np


In [ ]:
# creamos un array de 10 numeros de 0 a 10

In [2]:

np.arange(0,10)
           

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creamos un array de 2 en 2 hasta el 20 , el ultimo numero no la saca

In [3]:
np.arange (0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# creamos un array de fila (10) columna (5 )de solo 0000

In [6]:
np.zeros ((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# creamos un array de fila (10) columnas(5) de 1111 etc

In [7]:
np.ones ((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# nos da un array de 100 del 0 al 10

In [8]:
np.linspace (0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
# nos da 4 columnas y cuatros filas, la linia diagonal central de unos

In [10]:
np.eye (4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# nos da un numero decimal aleatorio

In [15]:
np.random.rand ()

0.21074790291207401

In [ ]:
# nos da cuatro numeros decimales aleatorios

In [16]:
np.random.rand (4)

array([0.58331073, 0.12673312, 0.17783111, 0.0649914 ])

In [ ]:
# nos da 4 filas y 40columnas de decimales aleatorios

In [17]:
np.random.rand (4,4)

array([[0.88772486, 0.9698661 , 0.53257244, 0.45768377],
       [0.80081662, 0.03325576, 0.99873029, 0.3675079 ],
       [0.84861983, 0.99796448, 0.94473067, 0.45262868],
       [0.41021038, 0.55514346, 0.32415446, 0.81132792]])

In [ ]:
# nos da un array del 1 al 15 aleatorio

In [26]:
np.random.randint (1,15)

11

In [ ]:
#nos da 10 columnas y 10 filas del 1 al 100 aleatorios

In [27]:
np.random.randint (1,100,(10,10))

array([[18, 13, 59, 22, 87, 96, 17, 25, 71, 92],
       [11, 91, 84, 86, 17, 81, 20, 75, 13, 43],
       [71, 60, 10,  4, 77, 22, 68, 65, 13, 81],
       [12, 97, 34, 37,  8, 20, 55, 28, 98, 80],
       [ 9, 79, 98,  3,  6, 33, 91, 69, 56, 17],
       [81, 97, 37, 54, 51, 42, 30, 26, 70, 19],
       [15, 30, 51, 86, 17, 40, 55, 25, 76, 99],
       [13, 22, 50, 60, 18, 23,  3, 73, 11, 72],
       [56, 47, 56, 47,  5, 20, 71, 28, 55, 43],
       [92, 76,  7, 96, 14,  2, 53, 62, 50, 33]])