In [5]:
import numpy as np

In [6]:
lista=[1,2,3,4,5,6,7,8,9,]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr= np.array(lista)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [35]:
matriz= [1,2,3],[4,5,6],[7,8,9]
matriz= np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#[] a nivel de indexado

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [38]:
arr[1]

1

In [39]:
arr[1]+arr[5]

6

In [40]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matriz[1,1]

5

In [47]:
matriz[1:2]

array([[4, 5, 6]])

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [ ]:
# Slicing nos permite extraer varios datos , tiene un comienzo y un final
# En este ejemplo se esta extrayendo datos desde la posicion 1 hasta la 5

In [51]:
arr[1:5]

array([1, 2, 3, 4], dtype=int8)

In [52]:
arr[2:]

array([2, 3, 4, 5, 6], dtype=int8)

In [ ]:
# trae todo pero de 3 en 3

In [53]:
arr[::3]

array([0, 3, 6], dtype=int8)

In [ ]:
#cuando se le asigna un valor negativo se regresan los valores comenzand des la ultima posición del array.

In [54]:
arr[-3:]

array([4, 5, 6], dtype=int8)

In [56]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# aqui nos trae desde la primera fila en adelante y la columna 0 a la 2

In [57]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [59]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
matriz[2,1:2]

array([8])

In [72]:
matriz=([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[9,10,11,12,],[13,14,15,16],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12,]]])
matriz=np.array(matriz)
matriz

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [73]:
matriz.ndim

3

In [74]:
matriz

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [81]:
matriz[0,:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [84]:
matriz[1,:,1:2]

array([[10],
       [14],
       [10]])

In [ ]:
# cambiando el tipo de dato

In [5]:
arr = np.array([1,2,3,4,5,6], dtype='float')
arr.dtype



dtype('float64')

In [11]:
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
arr = np.array([1,2,3,4,5,6])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5., 6.])

In [13]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True])

In [14]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S11')

In [15]:
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S11')

In [16]:
arr = np.array(['0','1','2','3','4','5','6'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [ ]:
# DIMENSIONES


In [17]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [18]:
vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [ ]:
# Definiendo matriz

In [19]:
matriz = np.array ([[1,2,3], [4,5,6]])
print (matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [20]:
matriz= np.array ([[1,2,3], [4,5,6],[7,8,9],[0,2,45]])
print (matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0  2 45]]


2

In [21]:
# creando un array con un tensor de 3 dimensiones

In [22]:
tensor = np.array ([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print (tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

In [23]:
# agregar o eliminar dimensiones


In [24]:
vector = np.array ([1,2,3],ndmin =10)
print (vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [25]:
# expandir la dimencion

In [26]:
expand = np.expand_dims(np.array([1,2,3]),axis =0)
print (expand)
expand.ndim

[[1 2 3]]


2

In [27]:
# eliminar dimensiones que no estoy usando

In [28]:
print (vector , vector.ndim)
vector_2 = np.squeeze(vector)
print (vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [29]:
# trabajo practico
 

In [30]:
tensor_1= np.array ([[[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]]])
print (tensor_1)
tensor_1.ndim

[[[[[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]

   [[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]

   [[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]]]]


5

In [88]:
tensor_2 = np.array ([1,2,3,4],ndmin =5)
print (tensor_2)
tensor_2.ndim

[[[[[1 2 3 4]]]]]


5

In [85]:
expand=np.expand_dims(np.array([[[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]]]),axis=0)
print(expand)
expand.ndim


[[[[[[1 2 3 4]
     [1 2 3 4]
     [1 2 3 4]]

    [[1 2 3 4]
     [1 2 3 4]
     [1 2 3 4]]

    [[1 2 3 4]
     [1 2 3 4]
     [1 2 3 4]]]]]]


6

In [87]:
print (tensor_1, tensor_1.ndim)
tensores = np.squeeze (tensor_1)
print ( tensores ,tensores.ndim)


[[1]
 [2]
 [3]
 [4]] 2
[1 2 3 4] 1


In [89]:
tensor_1 = np.expand_dims (np.array ([1,2,3,4]), axis = 1)
print (tensor_1)
tensor_1.ndim

[[1]
 [2]
 [3]
 [4]]


2

In [90]:
print (tensor_2, tensor_2.ndim)

[[[[[1 2 3 4]]]]] 5
