In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [5]:
arr =np.array ([1,2,3,4,5,6], dtype='float')
arr.dtype



dtype('float64')

In [7]:
arr

array([1., 2., 3., 4., 5., 6.])

In [6]:
arr =np.array ([1,2,3,4,5,6])
arr = arr.astype (np.float64)
arr

array([1., 2., 3., 4., 5., 6.])

In [10]:
arr =np.array ([0,1,2,3,4,5,6])
arr = arr.astype (np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True])

In [14]:
arr =np.array ([0,1,2,3,4,5,6])
arr = arr.astype (np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S11')

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [17]:
arr =np.array (['0','1','2','3','4','5','6'])
arr = arr.astype (np.int8)
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [18]:
scalar = np.array (42)
print (scalar)
scalar.ndim

42


0

In [19]:
vector= np.array([1,2,3,4])
print (vector)
vector.ndim

[1 2 3 4]


1