In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
arr.dtype

dtype('int32')

In [ ]:
# cambiando el tipo de dato

In [5]:
arr = np.array([1,2,3,4,5,6], dtype='float')
arr.dtype



dtype('float64')

In [7]:
arr

array([1., 2., 3., 4., 5., 6.])

In [6]:
arr = np.array([1,2,3,4,5,6])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5., 6.])

In [10]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True])

In [14]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S11')

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [17]:
arr = np.array(['0','1','2','3','4','5','6'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)

In [18]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [19]:
vector = np.array([1,2,3,4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [2]:
matriz = np.array ([[1,2,3], [4,5,6]])
print (matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
matriz= np.array ([[1,2,3], [4,5,6],[7,8,9],[0,2,45]])
print (matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0  2 45]]


2

In [ ]:
# creando un array con un tensor de 3 dimensiones

In [13]:
tensor = np.array ([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print (tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

In [ ]:
# agregar o eliminar dimensiones


In [19]:
vector = np.array ([1,2,3],ndmin =10)
print (vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
# expandir la dimencion

In [23]:
expand = np.expand_dims(np.array([1,2,3]),axis =0)
print (expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
# eliminar dimensiones que no estoy usando

In [24]:
print (vector , vector.ndim)
vector_2 = np.squeeze(vector)
print (vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [25]:
# trabajo practico
 

In [38]:
tensor_1= np.array ([[[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]]])
print (tensor_1)
tensor_1.ndim

[[[[[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]

   [[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]

   [[1 2 3 4]
    [1 2 3 4]
    [1 2 3 4]]]]]


5

In [51]:
tensor_2 = np.array ([1,2,3,4],ndmin =5)
print (tensor_2)
tensor_2.ndim

[[[[[1 2 3 4]]]]]


5

In [55]:
print (tensor_2, tensor_2.ndim)
tensores = np.squeeze (tensor_2)
print ( tensores ,tensores.ndim)


[[[[[1 2 3 4]]]]] 5
[1 2 3 4] 1


In [47]:
tensor_1 = np.expand_dims (np.array ([1,2,3,4]), axis = 1)
print (tensor_1)
tensor_1.ndim

[[1]
 [2]
 [3]
 [4]]


2

In [50]:
print (tensor_2, tensor_2.ndim)

[1 2 3 4] 1
