In [1]:
import numpy as np

In [4]:
arr=np.random.randint (1,20,10)


In [5]:
matriz = arr.reshape (2,5)
matriz

array([[17,  7, 15,  4,  1],
       [ 3, 11,  1,  5, 10]])

In [9]:
arr

array([17,  7, 15,  4,  1,  3, 11,  1,  5, 10])

In [7]:
arr.max()

17

In [10]:
matriz

array([[17,  7, 15,  4,  1],
       [ 3, 11,  1,  5, 10]])

In [12]:
matriz.max()

17

In [ ]:
# numero maximo por el eje 0 que escoge el numero mayor de cada columna

In [13]:
matriz.max(0)

array([17, 11, 15,  5, 10])

In [ ]:
# selecciona el mayor por el eje uno(1) que escoge el numero mayor por cada fila

In [14]:
matriz.max(1)

array([17, 11])

In [17]:
arr

array([17,  7, 15,  4,  1,  3, 11,  1,  5, 10])

In [18]:
arr.argmax()

0

In [19]:
arr.min()

1

In [23]:
arr.argmin()

4

In [26]:
matriz.argmax(0)

array([0, 1, 0, 1, 1], dtype=int64)

In [28]:
matriz.min(0)

array([3, 7, 1, 4, 1])

In [29]:
matriz.argmin(1)

array([4, 2], dtype=int64)

In [30]:
arr

array([17,  7, 15,  4,  1,  3, 11,  1,  5, 10])

In [31]:
arr.ptp()

16

In [32]:
matriz

array([[17,  7, 15,  4,  1],
       [ 3, 11,  1,  5, 10]])

In [33]:
matriz.ptp(0)

array([14,  4, 14,  1,  9])

In [37]:
arr

array([17,  7, 15,  4,  1,  3, 11,  1,  5, 10])

In [35]:
np.percentile (arr,50)

6.0

In [36]:
np.percentile (arr,0)

1.0

In [42]:
arr.sort()
arr

array([ 1,  1,  3,  4,  5,  7, 10, 11, 15, 17])

In [43]:
np.percentile (arr,50)

6.0

In [45]:
np.median(arr)


6.0

In [46]:
np.median(matriz,0)

array([ 4. ,  5.5,  7. ,  9.5, 11. ])

In [47]:
np.median(matriz,1)

array([ 3., 11.])

In [48]:
np.std(arr)

5.370288632839021

In [50]:
np.std(arr)**2

28.839999999999996

In [49]:
np.var(arr)

28.839999999999996

In [51]:
np.mean(arr)

7.4

In [52]:
np.mean(matriz,0)

array([ 4. ,  5.5,  7. ,  9.5, 11. ])

In [117]:
a = np.array([[1,2,],[3,4]])
b = np.array ([5,6])
a.ndim
b.ndim



1

In [118]:
b= np.expand_dims(b,axis=0)

In [119]:

c= np.concatenate ((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [124]:
c= np.concatenate((a,b.T),axis=1)
c

array([[1, 2, 5],
       [3, 4, 6]])

In [125]:
b.T

array([[5],
       [6]])