In [1]:
import numpy as np


In [ ]:
# Existen diferentes operaciones que se pueden usar para los arrays de Numpy.

In [3]:
lista = [1,2]
lista

[1, 2]

In [ ]:
# Numpy lo entiende mucho mejor

In [4]:
arr = np.arange (0,10)
arr2 = arr.copy ()

In [ ]:
# ahora multiplicamos por un vector.

In [30]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# División con un vector.
# Como en este caso la primera posición del array 0, muestra un error, pero no detiene el proceso

In [29]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_18640\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# elevar a un vector

In [8]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Sumar dos arrays de igual dimensiones las hace elemto por elemento.

In [9]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# lo mismo aplica para las matrices

In [20]:
matriz= arr.reshape (2,5)
matriz2 = matriz.copy()

In [11]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matriz + matriz2


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [24]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [23]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#hacer la transpuesta de matriz2 .Una operacion importante es la de punto a punto, dos formas de hacerlo

In [26]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [27]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [28]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])