In [5]:
import numpy as np

In [7]:
arr = np.random.randint (1,10,(3,2))
arr

array([[2, 4],
       [7, 4],
       [3, 8]])

In [ ]:
# aplicando con shape: nos dice cuantas filas y columnas tenemos en el array

In [6]:
arr.shape


(3, 2)

In [8]:
arr

array([[2, 4],
       [7, 4],
       [3, 8]])

In [ ]:
#Rasahape nos ayuda acambiar la forma de nuestro codigo, pero no las cantidades

In [9]:
arr.reshape (1,6)

array([[2, 4, 7, 4, 3, 8]])

In [10]:
arr.reshape (2,3)

array([[8, 7, 2],
       [5, 7, 2]])

In [11]:
np.reshape (arr, (1,6))

array([[8, 7, 2, 5, 7, 2]])

In [ ]:
# como esta ordenando al momento de hacer reshape con el lenguaje "original c"
# LO ORDEENA `POR FILAS`

In [12]:
np.reshape (arr, (2,3), 'C')

array([[8, 7, 2],
       [5, 7, 2]])

In [14]:
arr.reshape (2,3 ),'C'

(array([[8, 7, 2],
        [5, 7, 2]]),
 'C')

In [ ]:
# por el lenguaje Fortran ordena por columnas

In [15]:
np.reshape (arr, (2,3), 'F')

array([[8, 7, 5],
       [2, 7, 2]])

In [16]:
arr.reshape (2,3) , 'F'

(array([[8, 7, 2],
        [5, 7, 2]]),
 'F')

In [ ]:
# como esta optimizado el almacenamiento en mi sistema 'A', puede ser 'F' O 'C'.
# com el comando 'A' se optimaza tiempo , pero es mejor hacerlo con el metodo 'C'

In [17]:
np.reshape (arr,(2,3),'A')

array([[8, 7, 2],
       [5, 7, 2]])

In [ ]:
# trabajo : crear un array de cualquier tipo de dimensión y cambiar su tipo de dimensión

In [10]:
array=np.array ([[20,30,40],[50,60,70]])

In [11]:
array

array([[20, 30, 40],
       [50, 60, 70]])

In [12]:
array.shape

(2, 3)

In [13]:
array

array([[20, 30, 40],
       [50, 60, 70]])

In [21]:
array.reshape (3,2)

array([[20, 30],
       [40, 50],
       [60, 70]])

In [22]:
array.reshape (3,2), 'C'

(array([[20, 30],
        [40, 50],
        [60, 70]]),
 'C')

In [23]:
array.reshape (3,2) , 'F'

(array([[20, 30],
        [40, 50],
        [60, 70]]),
 'F')

In [25]:
np.reshape (array,(3,2),'A')

array([[20, 30],
       [40, 50],
       [60, 70]])