In [31]:
import numpy as np

In [32]:
arr = np.random.randint (1,10,(3,2))
arr

array([[6, 1],
       [9, 7],
       [2, 1]])

In [33]:
# aplicando con shape: nos dice cuantas filas y columnas tenemos en el array

In [34]:
arr.shape


(3, 2)

In [35]:
arr

array([[6, 1],
       [9, 7],
       [2, 1]])

In [36]:
#Rasahape nos ayuda acambiar la forma de nuestro codigo, pero no las cantidades

In [37]:
arr.reshape (1,6)

array([[6, 1, 9, 7, 2, 1]])

In [38]:
arr.reshape (2,3)

array([[6, 1, 9],
       [7, 2, 1]])

In [39]:
np.reshape (arr, (1,6))

array([[6, 1, 9, 7, 2, 1]])

In [ ]:
# como esta ordenando al momento de hacer reshape con el lenguaje "original c"
# LO ORDEENA `POR FILAS`

In [40]:
arr

array([[6, 1],
       [9, 7],
       [2, 1]])

In [42]:
np.reshape (arr, (2,3),)

array([[6, 1, 9],
       [7, 2, 1]])

In [44]:
arr

array([[6, 1],
       [9, 7],
       [2, 1]])

In [45]:
arr.reshape (2,3 ),'C'

(array([[6, 1, 9],
        [7, 2, 1]]),
 'C')

In [ ]:
# por el lenguaje Fortran ordena por columnas

In [46]:
np.reshape (arr, (2,3), 'F')

array([[6, 2, 7],
       [9, 1, 1]])

In [47]:
arr.reshape (2,3) , 'F'

(array([[6, 1, 9],
        [7, 2, 1]]),
 'F')

In [ ]:
# como esta optimizado el almacenamiento en mi sistema 'A', puede ser 'F' O 'C'.
# com el comando 'A' se optimaza tiempo , pero es mejor hacerlo con el metodo 'C'

In [48]:
np.reshape (arr,(2,3),'A')

array([[6, 1, 9],
       [7, 2, 1]])

In [ ]:
# trabajo : crear un array de cualquier tipo de dimensión y cambiar su tipo de dimensión

In [10]:
array=np.array ([[20,30,40],[50,60,70]])

In [11]:
array

array([[20, 30, 40],
       [50, 60, 70]])

In [12]:
array.shape

(2, 3)

In [49]:
array

array([[20, 30, 40],
       [50, 60, 70]])

In [50]:
array.reshape (1,6)

array([[20, 30, 40, 50, 60, 70]])

In [51]:
array.reshape (1,6), 'C'

(array([[20, 30, 40, 50, 60, 70]]), 'C')

In [52]:
array.reshape (3,2) , 'F'

(array([[20, 30],
        [40, 50],
        [60, 70]]),
 'F')

In [53]:
np.reshape (array,(3,2),'A')

array([[20, 30],
       [40, 50],
       [60, 70]])