In [2]:
import numpy as np

In [5]:
arr = np.random.randint (1,10,(3,2))
arr

array([[8, 7],
       [2, 5],
       [7, 2]])

In [ ]:
# aplicando con shape: nos dice cuantas filas y columnas tenemos en el array

In [6]:
arr.shape


(3, 2)

In [7]:
arr

array([[8, 7],
       [2, 5],
       [7, 2]])

In [ ]:
#Rasahape nos ayuda acambiar la forma de nuestro codigo, pero no las cantidades

In [8]:
arr.reshape (1,6)

array([[8, 7, 2, 5, 7, 2]])

In [10]:
arr.reshape (2,3)

array([[8, 7, 2],
       [5, 7, 2]])

In [11]:
np.reshape (arr, (1,6))

array([[8, 7, 2, 5, 7, 2]])

In [ ]:
# como esta ordenando al momento de hacer reshape con el lenguaje "original c"
# LO ORDEENA `POR FILAS`

In [12]:
np.reshape (arr, (2,3), 'C')

array([[8, 7, 2],
       [5, 7, 2]])

In [14]:
arr.reshape (2,3 ),'C'

(array([[8, 7, 2],
        [5, 7, 2]]),
 'C')

In [ ]:
# por el lenguaje Fortran ordena por columnas

In [15]:
np.reshape (arr, (2,3), 'F')

array([[8, 7, 5],
       [2, 7, 2]])

In [16]:
arr.reshape (2,3) , 'F'

(array([[8, 7, 2],
        [5, 7, 2]]),
 'F')

In [ ]:
# como esta optimizado el almacenamiento en mi sistema 'A', puede ser 'F' O 'C'.
# com el comando 'A' se optimaza tiempo , pero es mejor hacerlo con el metodo 'C'

In [17]:
np.reshape (arr,(2,3),'A')

array([[8, 7, 2],
       [5, 7, 2]])

In [ ]:
# trabajo : crear un array de cualquier tipo de dimensión y cambiar su tipo de dimensión

In [27]:
trabajo =np.array ([[20,30,40],[50,60,70],[40,50,58]])

In [28]:
trabajo

array([[20, 30, 40],
       [50, 60, 70],
       [40, 50, 58]])

In [29]:
trabajo.shape

(3, 3)

In [30]:
trabajo

array([[20, 30, 40],
       [50, 60, 70],
       [40, 50, 58]])

In [35]:
trabajo.shape

(3, 3)

In [37]:
trabajo

array([[20, 30, 40],
       [50, 60, 70],
       [40, 50, 58]])

In [46]:
trabajo.reshape (3,3)

array([[20, 30, 40],
       [50, 60, 70],
       [40, 50, 58]])

In [49]:
trabajo.reshape (3,3), 'C'

(array([[20, 30, 40],
        [50, 60, 70],
        [40, 50, 58]]),
 'C')

In [52]:
trabajo.reshape (3,3) , 'F'

(array([[20, 30, 40],
        [50, 60, 70],
        [40, 50, 58]]),
 'F')